version: 2.1

executors:
  books_app_executor:
    docker:
      - image: circleci/ruby:2.6.2-node-browsers
    environment:
      BUNDLE_PATH: vendor/bundle
    working_directory: ~/repo

commands:
  bundle_install:
    steps:
      - run:
          name: Bundler install
          command: gem install bundler
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

jobs:
  minitest:
    executor: books_app_executor
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - bundle_install
      - run:
          name: Database setup
          command: bundle exec rake db:create db:migrate
      - run: 
          name: Run tests
          command: bundle exec rake test
      - store_test_results:
          path: test/reports

  deploy:
    executor: books_app_executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "22:7c:45:f1:6c:34:b0:fa:93:0b:1a:ea:38:29:e6:c1"
      - checkout
      - bundle_install
      - run:
          name: Capistrano deploy
          command: bundle exec cap production deploy

workflows:
  version: 2
  minitest_and_deploy:
    jobs:
      - minitest
      - deploy:
          requires:
            - minitest
          filters:
            branches:
              only: master
